"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { PageHeader } from "@/components/PageHeader";
import {
  Bell,
  CheckCircle2,
  ExternalLink,
  Loader2,
  Clock,
  ArrowRight,
  Check,
} from "lucide-react";

export default function OwnerNotificationsPage() {
  const [notifications, setNotifications] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  const loadNotifications = async () => {
    try {
      setLoading(true);
      const res = await fetch("/api/owner/notifications");
      if (res.ok) {
        const json = await res.json();
        setNotifications(json.notifications || []);
      }
    } catch (err) {
      console.error("Failed to load notifications", err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadNotifications();
  }, []);

  const handleMarkAllRead = async () => {
    try {
      await fetch("/api/owner/notifications", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ markAll: true }),
      });
      loadNotifications();
    } catch (err) {
      console.error("Failed to mark notifications read", err);
    }
  };

  const handleMarkOne = async (id: string) => {
    try {
      await fetch("/api/owner/notifications", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ notificationId: id }),
      });
      loadNotifications();
    } catch (err) {
      console.error("Failed to mark notification read", err);
    }
  };

  return (
    <div>
      <PageHeader
        title="Notifications"
        description="Persistent event-driven intelligence alerts for brand verification milestones, completed investigations, and shared reports."
        fallbackBackUrl="/owner"
        breadcrumbs={[{ label: "Overview", href: "/owner" }, { label: "Notifications" }]}
        actions={
          notifications.some((n) => !n.read_status) && (
            <button
              onClick={handleMarkAllRead}
              className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold bg-white hover:bg-surface-warm text-charcoal-700 border border-surface-border transition-colors shadow-sm cursor-pointer"
            >
              <Check className="w-3.5 h-3.5" />
              <span>Mark all as read</span>
            </button>
          )
        }
      />

      {loading ? (
        <div className="py-20 text-center">
          <Loader2 className="w-8 h-8 animate-spin mx-auto text-charcoal-400 mb-3" />
          <p className="text-xs text-charcoal-500 font-mono">Loading notifications...</p>
        </div>
      ) : notifications.length === 0 ? (
        <div className="p-12 text-center bg-white rounded-xl border border-surface-border shadow-card">
          <Bell className="w-8 h-8 text-charcoal-400 mx-auto mb-2" />
          <p className="text-sm font-semibold text-charcoal-700">No notifications on record</p>
          <p className="text-xs text-charcoal-500 mt-1 max-w-sm mx-auto">
            System alerts generated by actual platform events will appear here in chronological order.
          </p>
        </div>
      ) : (
        <div className="space-y-3">
          {notifications.map((n) => (
            <div
              key={n.id}
              className={`p-4 rounded-xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-4 ${
                n.read_status
                  ? "bg-white border-surface-border text-charcoal-700"
                  : "bg-butter-50/60 border-butter-300 text-charcoal-900 shadow-sm"
              }`}
            >
              <div className="flex items-start gap-3">
                <div
                  className={`w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0 mt-0.5 ${
                    n.read_status
                      ? "bg-surface-warm text-charcoal-500 border border-surface-border"
                      : "bg-butter-400 text-charcoal-900 border border-butter-500/40"
                  }`}
                >
                  <Bell className="w-4 h-4" />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <h4 className="font-bold text-xs text-charcoal-900">{n.title}</h4>
                    {!n.read_status && (
                      <span className="w-2 h-2 rounded-full bg-butter-500" />
                    )}
                  </div>
                  <p className="text-xs text-charcoal-600 mt-0.5 leading-relaxed">{n.message}</p>
                  <span className="text-[10px] text-charcoal-400 font-mono mt-1 block">
                    {new Date(n.created_at).toLocaleString()}
                  </span>
                </div>
              </div>

              <div className="flex items-center gap-2 self-end sm:self-center">
                {n.link && (
                  <Link
                    href={n.link}
                    onClick={() => !n.read_status && handleMarkOne(n.id)}
                    className="inline-flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-semibold bg-white hover:bg-surface-warm border border-surface-border text-charcoal-900 transition-colors"
                  >
                    <span>View Record</span>
                    <ArrowRight className="w-3 h-3 text-charcoal-600" />
                  </Link>
                )}

                {!n.read_status && (
                  <button
                    onClick={() => handleMarkOne(n.id)}
                    className="p-1.5 text-charcoal-400 hover:text-charcoal-900 rounded-lg hover:bg-surface-warm transition-colors"
                    title="Mark as read"
                  >
                    <Check className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
